do $$
begin
  if not exists (
    select 1
    from pg_attribute
    where attrelid = 'public.match_reminders'::regclass
      and attname = 'id'
      and attidentity <> ''
  ) then
    alter table public.match_reminders
      alter column id add generated by default as identity;
  end if;
end;
$$;

select setval(
  pg_get_serial_sequence('public.match_reminders', 'id'),
  coalesce((select max(id) from public.match_reminders), 0) + 1,
  false
);
