-- Add optional tournament grouping without duplicating match records.
create table if not exists public.tournaments (
    id bigint generated by default as identity primary key,
    name text not null check (char_length(trim(name)) between 1 and 160),
    description text,
    start_date date,
    end_date date,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint tournaments_date_order_check check (
        start_date is null or end_date is null or end_date >= start_date
    )
);

alter table public.matches
    add column if not exists tournament_id bigint references public.tournaments(id) on delete set null;

create index if not exists matches_tournament_id_idx
    on public.matches (tournament_id, match_start_at);

alter table public.tournaments enable row level security;

drop policy if exists "Anyone can view active tournaments" on public.tournaments;
create policy "Anyone can view active tournaments"
on public.tournaments
for select
to anon, authenticated
using (is_active = true);

drop policy if exists "Admin can manage tournaments" on public.tournaments;
create policy "Admin can manage tournaments"
on public.tournaments
for all
to authenticated
using (
    auth.uid() = '749c0b4a-ae6d-41cc-b046-1695089f191c'::uuid
    and (auth.jwt() ->> 'aal') = 'aal2'
)
with check (
    auth.uid() = '749c0b4a-ae6d-41cc-b046-1695089f191c'::uuid
    and (auth.jwt() ->> 'aal') = 'aal2'
);

grant select on table public.tournaments to anon, authenticated;
grant insert, update, delete on table public.tournaments to authenticated;
grant usage, select on sequence public.tournaments_id_seq to authenticated;

drop policy if exists "Admin can assign tournament to matches" on public.matches;
create policy "Admin can assign tournament to matches"
on public.matches
as restrictive
for update
to authenticated
using (
    auth.uid() = '749c0b4a-ae6d-41cc-b046-1695089f191c'::uuid
    and (auth.jwt() ->> 'aal') = 'aal2'
)
with check (
    auth.uid() = '749c0b4a-ae6d-41cc-b046-1695089f191c'::uuid
    and (auth.jwt() ->> 'aal') = 'aal2'
);
